kind: Deployment
apiVersion: apps/v1
metadata:
  name: dummy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      deploy: dummy-app
  template:
    metadata:
      labels:
        deploy: dummy-app
    spec:
      volumes:
        - name: envoy-config
          configMap:
            name: envoy-cm
        - name: server-cert
          configMap:
            name: server-cert-cm
        - name: server-key
          configMap:
            name: server-key-cm
        - name: ca-cert
          configMap:
            name: ca-cert-cm
      containers:
        - name: envoy-proxy
          image: envoyproxy/envoy:v1.31.3
          args:
            - "-c"
            - "/config/envoy.yaml"
          volumeMounts:
            - readOnly: true
              mountPath: /config
              name: envoy-config
            - readOnly: true
              mountPath: /certs/server-cert
              name: server-cert
            - readOnly: true
              mountPath: /certs/server-key
              name: server-key
            - readOnly: true
              mountPath: /certs/ca-cert
              name: ca-cert
        - name: netshoot
          image: nicolaka/netshoot
          command: ["/bin/sleep", "3650d"]
          # then run `update-ca-certificates` to load CA certificate
          volumeMounts:
            - readOnly: true
              mountPath: /usr/local/share/ca-certificates/
              name: ca-cert
        - name: go-httpbin-server-1
          image: sjulian/go-httpbin:v0.0.1
          env:
            - name: SERVER_PORT
              value: "8081"
            - name: SERVER_NAME
              value: "SERVER_1"
        - name: go-httpbin-server-2
          image: sjulian/go-httpbin:v0.0.1
          env:
            - name: SERVER_PORT
              value: "8082"
            - name: SERVER_NAME
              value: "SERVER_2"
          
          

          